### PR TITLE
Adding module files for podman images

### PR DESCRIPTION
**Pull request by renuHadke**
Signed-off-by: renuhadke <hadke.r@husky.neu.edu>

### CODE REVIEW

**Comment by rhatdan** [comment]
@ipbabble PTAL

**Comment by ipbabble** [comment]
Sí. On pto but will look

**Comment by rhatdan** [comment]
@tomsweeneyredhat @jwhonce PTAL

**Comment by rhatdan** [comment]
@renuHadke You need to rebase your PR, you should not include the Merge.

**Comment by ipbabble** [comment]
@claudiol  you should look at this too. LGTM.

**Pull request merged**
