### PR TITLE
Adding playbook to pull image.

### PR DESCRIPTION
**Pull request by Phadated**
Signed-off-by: Dhanisha Phadate <phadate.d@husky.neu.edu>

### CODE REVIEW

**Comment by rhatdan** [comment]
@Phadated Could you get others from your team to do reviews?

**Comment by Phadated** [comment]
@renuHadke @nehajain1809 @ckeskar @krishjain4894  Please review the PR's

**Comment by krishjain4894** [comment]
Hi Dhanisha
Looks Good to me !!

**Comment by nehajain1809** [comment]
@Phadated LGTM. The playbook is running fine.

**Pull request merged**
